image: "python:3.8"

before_script:
  - apt install pkg-config
  - python --version
  - python -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt
  - pip install pytest
  - pip install '.[test]'

stages:
  - Test

pytest:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - export FLASK_APP=pdfextractor
  - export FLASK_ENV=development
  - pytest