image: "python:3.8"

before_script:
  - python3 --version
  - python3 -m venv venv
  - . venv/bin/activate
  - pip3 install -e . --quiet
  - pip3 install pytest
  - pip3 install '.[test]'

stages:
  - Test

pytest:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python3 -c "import sys;print(sys.path)"
  - export FLASK_APP=pdfextractor
  - export FLASK_ENV=development
  - pytest