image: "python:3.8"

before_script:
  - python --version
  - pip install -e . --quiet
  - pip install pytest

stages:
  - Test

pytest:
  stage: Test
  script:
  - pytest

#stages:
#  - test

#test job:
#  stage: test
#  script:
#    - export PYTHONPATH=.
#    - export FLASK_APP=pdfextractor
#    - export FLASK_ENV=development
#    - pip install -e --quiet .
#    - pytest