image: "python:3.8"

before_script:
  - python --version
  - python -m venv venv
  - . venv/bin/activate
  - pip install -e . --quiet
  - pip install pytest
  - pip install '.[test]'

stages:
  - Test

pytest:
  stage: Test
  script:
  - export PYTHONPATH=.
  - export FLASK_APP=pdfextractor
  - export FLASK_ENV=development
  - pytest