stages:
  - test

test job:
  stage: test
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=pdfextractor
    - export FLASK_ENV=development
    - apt-get update -qy
    - pip install -e .
    - pytest